### ISSUE TITLE
Ticking Entity on Evolved Enderman spawn

### ISSUE THREAD

**Issue by xAlicatt** [p455w0rd/EndermanEvolution#1]
This crashes my singleplayer world when an Evolved Enderman naturally spawns or when spawned in with a mob egg. I haven't had a chance to check the Frienderman yet. I will check that and also I will try disabling the mods that affect mobs, like AS's Infernal Mobs (and maybe Baby Mobs???? ¯\_(ツ)_/¯) and report back.

EDIT:: Crash to desktop with the same crash report with Infernal Mobs and In Control! removed.

java.lang.IllegalAccessError: tried to access field net.minecraft.entity.EntityLivingBase.field_70773_bE from class p455w0rd.endermanevo.entity.EntityEvolvedEnderman
	at p455w0rd.endermanevo.entity.EntityEvolvedEnderman.func_70636_d(EntityEvolvedEnderman.java:363)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2167)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1986)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
	at net.minecraft.world.World.func_72870_g(World.java:1948)
	at net.minecraft.world.World.func_72939_s(World.java:1755)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

**Comment by Morpheus1101** [comment]
Can confirm this occurs

**Comment by p455w0rd** [comment]
please use pastebin or something when posting a log..i forgot to add the AT info..thanks for reporting

**Comment by p455w0rd** [comment]
https://minecraft.curseforge.com/projects/enderman-evolution/files/2514346
